server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#



#  jpa:
##    database-platform: org.hibernate.dialect.HSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#spring.mvc.static-path-pattern: /**
#spring.resources.static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/,classpath:/public/
#
#
